# Generated by Django 2.2.6 on 2019-11-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaceEncoding',
            new_name='FaceEncodingModel',
        ),
    ]
