# Generated by Django 2.2.6 on 2019-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facemodel',
            name='slug',
            field=models.SlugField(default='123', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recognizedpersonmodel',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
