# Generated by Django 2.2.6 on 2019-11-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20191103_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facemodel',
            old_name='recognized_person',
            new_name='person',
        ),
    ]
