# Generated by Django 2.2.6 on 2019-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20191128_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedpersonmodel',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
