# Generated by Django 2.2.6 on 2019-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20191105_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_path',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
    ]
