# Generated by Django 2.2.6 on 2019-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20191105_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='thumbnails/'),
        ),
    ]
