# Generated by Django 2.2.6 on 2019-11-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_imagemodel_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facemodel',
            old_name='face_location',
            new_name='location',
        ),
    ]
