# Generated by Django 2.2.6 on 2019-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20191109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
