# Generated by Django 2.2.6 on 2019-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_imagemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedpersonmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recognizedpersonmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='recognizedpersonmodel',
            name='full_name',
            field=models.CharField(default='Patryk Wiener', max_length=100),
            preserve_default=False,
        ),
    ]
