# Generated by Django 2.2.6 on 2019-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20191115_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=10),
        ),
    ]
