# Generated by Django 2.2.6 on 2019-11-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20191115_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10),
        ),
    ]
