# Generated by Django 2.2.6 on 2019-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_auto_20191116_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
