# Generated by Django 2.2.6 on 2019-11-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20191118_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
    ]
