# Generated by Django 2.2.6 on 2019-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20191121_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
