# Generated by Django 2.2.6 on 2019-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20191121_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='date_time_taken',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
