# Generated by Django 2.2.6 on 2019-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0015_imagemodel_date_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='body',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
