# Generated by Django 2.2.6 on 2019-11-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0016_imagemodel_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='date_time_taken',
            new_name='datetime_taken',
        ),
    ]
