# Generated by Django 2.2.6 on 2019-11-25 17:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('image', '0017_auto_20191125_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
